apiVersion: v1
kind: Service
metadata:
  name: sikyon-backend
  labels:
    app: sikyon-backend
spec:
  type: ClusterIP
  selector:
    app: sikyon-backend
  ports:
    - name: http
      port: 3180
      targetPort: 3180
