---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: burnside
spec:
  encryptedData:
    .dockerconfigjson: AgBvntURgmh3cc3N/UEmeyErR3Di+ZYhZZ9mgrFCcbJCyCUbX770ToNgbJTPjXTONOsDnLhVSnBCmgopJvzUy4QQkB2oyuyzXHRQLIKfZIx6JZ59wQTEIL2jMBcjr+ltbVQ/BNW9V6cgiW2kRAdPP1HCEqRFPFf6j7d8Z5YxvX5I7OvScXtZdWlHF6aZ7HoZdnzu3G4rDubWp67/6w6Lb6lffAiwpOj7ER5nwgLXsj/xbiDsngJRMLKBFmqWBniO3UsTwrlTO9wx0NHlPO8komEMSal9L9+MDxmjLjWAfgunfJgfDMn4I2OKv3edNYylD2J8kIpi0oEIWNTf27dZUFeFgcgi8M1lne7aZKtVX4h4CCEaifDlV0oarDP82K3M4eWK9l94TzZ/rua/29a5iMmu8PQlSwN7vUUTkihXes9Peezz5WS3NOOv6kikCiuKAsrpiRXt+NckD5xVOunXto7BOqQfq3SkAn/F7Xh/TYxFW98YlKbjmuhQYHE+V4TkRKAGa1Jice8GsRUXKOY9ciCbpjnya5g41u2OQED9RwAVXlemN9a1hOnXEMyZplhMkwmZJ9lC9GdYtYXqlKFfs7JNVy4DEA+2bJLatfvaCjcAt7Wix//CAhq1DzptpTsMuAdGKumHuMXrBm4oDvIaFF7RacWWuX7qwKOUtzkPJG4miB5qnUvTxC5XcucIHa6mqpjW7ntn17YBEtQam+MuE6QO8K8o8wr+dKIg5NOWRKJD/gjpjG416pjlelwzQpWEE1iq6rOXR2h0vpq9dGbMOi+rwTBHz25I3updCgS9mHXTXs64EnywLpQtNPXANTKecwClaxs7+DBnynvE4lrMZEv1RP2gmtfQNkeJqOnXpLYcT6C92z713wbrPGX5xutEbAi3Qzp5LGdPbz5ZA4Jw3cYaP7fIHqAWiQEFQX/kAQh6U3Sa7/cn6LHDXanJaBcEhKMNOK5QbQhfO0YZMmdWqVAC0bnE2qPnHR0qyWC893NfadIQH1iRAfFkw38EpZLXOzYpQVuDAB8ltOVJOYFug4W8yVJxMwufbZ4pPbui2DKk7CZ1vDNiuDP8nDgV0265gnI3XwywqtsT0Gk=
  template:
    metadata:
      name: ghcr-secret
      namespace: burnside
    type: kubernetes.io/dockerconfigjson
