apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: burnside

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress-external.yaml

commonLabels:
  app.kubernetes.io/name: sikyon
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/mcharno/sikyon-backend
    newTag: latest
  - name: ghcr.io/mcharno/sikyon-frontend
    newTag: latest
